source 'https://rubygems.org'

base_path = ENV.fetch("JSII_BASE_PATH", "~/repos/aws-cdk")

gem 'jsii-ruby-runtime', path: "#{base_path}/jsii/packages/@jsii/ruby-runtime"
gem 'constructs', path: "#{base_path}/constructs/dist/ruby", require: false
gem 'aws-cdk-lib', path: "#{base_path}/aws-cdk/packages/aws-cdk-lib/dist/ruby", require: false
gem 'aws-cdk-asset-awscli-v1', path: "#{base_path}/aws-cdk/node_modules/@aws-cdk/asset-awscli-v1/dist/ruby", require: false
gem 'aws-cdk-asset-node-proxy-agent-v6', path: "#{base_path}/aws-cdk/node_modules/@aws-cdk/asset-node-proxy-agent-v6/dist/ruby", require: false
gem 'aws-cdk-cloud-assembly-schema', path: "#{base_path}/aws-cdk/node_modules/@aws-cdk/cloud-assembly-schema/dist/ruby", require: false
